name: build ui
on:  
  workflow_dispatch:
    inputs:
      environment:
        default: dev
        type: environment
        required: true
        description: Select the environment
  push:     
  pull_request:
    
jobs:
  build-ui:
    environment: ${{  github.event_name == 'push' && 'dev' || inputs.environment }}
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: docker login
        run: |                    
          echo "${{ secrets.OCIR_AUTH_TOKEN }}" | docker login --username ${{ secrets.OCIR_DOCKER_USER }} --password-stdin

      - name: create environment.ts         
        run: |
          cat > ui/src/environments/environment.ts <<EOF
          export const environment = {
          production: '',
          baseApiUrl: '',
          baseUrl: '',
          msalClientID: '',
          msalTenantID: '',
          msalResourceScopeID: '',
          mail: '',
          };
          EOF          
        shell: bash          

      - name: build and push to registry
        uses: docker/build-push-action@v6
        with:
          push: true
          context: .
          file: ./Dockerfile
          tags: ${{ secrets.OCIR_DOCKER_REGISTRY }}:v4

        