name: build UI
on:  
  workflow_dispatch:
    inputs:
      environment:
        default: dev
        type: environment
        required: true
        description: Select the environment
  push:
    
jobs:
  set-tag:
    outputs:
      BUILD_TAG: ${{ steps.set-tag.outputs.BUILD_TAG }}
    runs-on: ubuntu-latest
    steps:
      - name: Set tag
        id: set-tag
        run: echo "BUILD_TAG=$((date +"%Y%m%d%")" >> "$GITHUB_OUTPUT"

      # - name: Print output
      #   run: |          
      #     echo "111111111=steps.set-tag.outputs.BUILD_TAG"
      #     echo "111111111=$GITHUB_OUTPUT"

  # build-ui:
  #   environment: ${{  github.event_name == 'push' && 'dev' || inputs.environment }}
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: checkout
  #       uses: actions/checkout@v4

  #     - name: Docker login
  #       run: |                    
  #         echo "${{ secrets.OCIR_AUTH_TOKEN }}" | docker login --username ${{ secrets.OCIR_DOCKER_USER }} --password-stdin

  #     - name: create environment.ts
  #       run: |
  #         cat <<EOT > ui/src/environments/environment.ts
  #         export const environment = {
  #         production: '',
  #         baseApiUrl: '',
  #         baseUrl: '',
  #         msalClientID: '',
  #         msalTenantID: '',
  #         msalResourceScopeID: '',
  #         mail: '',
  #         };
  #         EOT
  #       shell: bash

  #     - name: Build and push to registry
  #       uses: docker/build-push-action@v6
  #       with:
  #         push: true
  #         context: .
  #         file: ./Dockerfile
  #         tags: ${{ secrets.OCIR_DOCKER_REGISTRY }}:v3

        